# -*- coding: utf-8 -*-
"""Stock Price Analysis and Financial Metrics Calculation using Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSN-ykXQn0uBpGgvBFXXAIR1sl7wUfxk
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Step 1: Fetch data for Tatamotors stock for the last 1 year
ticker = yf.Ticker("TATAMOTORS.NS")
data = ticker.history(period="1y")

# Step 2: Calculate daily returns
data['Daily_Return'] = data['Close'].pct_change()

# Step 3: Calculate 20-day and 50-day Simple Moving Averages (SMA)
data['SMA_20'] = data['Close'].rolling(window=20).mean()
data['SMA_50'] = data['Close'].rolling(window=50).mean()

# Step 4: Plot stock prices and moving averages
plt.figure(figsize=(12,6))
plt.plot(data['Close'], label='AAPL Close Price', color='blue')
plt.plot(data['SMA_20'], label='20-Day SMA', color='orange')
plt.plot(data['SMA_50'], label='50-Day SMA', color='green')
plt.title('TATAMOTORS Stock Price and Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price (INR)')
plt.legend()
plt.show()

# Step 5: Visualize daily returns
plt.figure(figsize=(10,6))
plt.hist(data['Daily Return'].dropna(), bins=50, alpha=0.75, color='blue')
plt.title('TATAMOTORS Daily Returns Distribution')
plt.xlabel('Daily Return')
plt.ylabel('Frequency')
plt.show()

# Display the first few rows of stock data
print("TATAMOTORS Stock Data (First 5 Rows):")
print(data.head())

# Step 2: Calculate daily returns
data['Daily_Return'] = data['Close'].pct_change()

print("\TATAMOTORS Stock Daily Returns (First 5 Rows):")
print(data[['Close', 'Daily_Return']].head())

# Step 3: Calculate 20-day and 50-day Simple Moving Averages (SMA)
data['SMA_20'] = data['Close'].rolling(window=20).mean()
data['SMA_50'] = data['Close'].rolling(window=50).mean()

# Display SMAs
print("\TATAMOTORS Stock Simple Moving Averages (First 5 Rows):")
print(data[['Close', 'SMA_20', 'SMA_50']].head())

# Step 4: Plot stock prices and moving averages
# Step 4: Plot stock prices and moving averages
plt.figure(figsize=(12,6))
plt.plot(data['Close'], label='TATAMOTORS Close Price', color='blue')
plt.plot(data['SMA_20'], label='20-Day SMA', color='orange')
plt.plot(data['SMA_50'], label='50-Day SMA', color='green')
plt.title('TATAMOTORS Stock Price and Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price (INR)')
plt.legend()
plt.show()

# Step 5: Visualize daily returns
plt.figure(figsize=(10,6))
plt.hist(data['Daily_Return'].dropna(), bins=50, alpha=0.75, color='blue')
plt.title('TATAMOTORS Daily Returns Distribution')
plt.xlabel('Daily_Return')
plt.ylabel('Frequency')
plt.show()

